language: go
go_import_path: github.com/shawguo-cn/archetype-golang
go:
 - 1.7.x

install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/ethereum/go-ethereum
 - go get github.com/stretchr/testify/assert
 - go get github.com/bitly/go-simplejson
script:
 - go test -v ./...