language: go
go_import_path: github.com/shawguo-cn/archetype-golang
go:
 - 1.7.x

install:
 - mkdir $GOPATH/bin
 - curl https://glide.sh/get | sh
 - glide update --strip-vendor --all-dependencies --skip-test
 - glide install
script:
 - go test -v ./...