language: go
go_import_path: github.com/shawguo-cn/archetype-golang
go:
 - 1.7.x

install:
 - mkdir $GOPATH/bin
 - mkdir -p /home/travis/.glide/cache/src/https-github.com-ethereum-go-ethereum/ethutil
 - curl https://glide.sh/get | sh
 - glide install
script:
 - go test -v ./...